name: Quora Poster

on:
  workflow_dispatch:   # enables "Run workflow" button
  repository_dispatch: # allows n8n or API trigger
    types: [post-quora]

jobs:
  post-to-quora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Quora automation
        run: node index.js
        env:
          QUORA_EMAIL: ${{ secrets.QUORA_EMAIL }}
          QUORA_PASSWORD: ${{ secrets.QUORA_PASSWORD }}
          BLOG_TITLE: ${{ github.event.inputs.title }}
          BLOG_URL: ${{ github.event.inputs.url }}
          BLOG_SUMMARY: ${{ github.event.inputs.summary }}
          KEYWORD: ${{ github.event.inputs.keyword }}
          MODE: ${{ github.event.inputs.mode }}
