name: Quora Automation

on:
  push:
    paths:
      - "latest-blog.json"   # Trigger only when blog JSON updates
  workflow_dispatch:         # Manual trigger option

jobs:
  quora-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer fs-extra

      - name: Run Quora Bot
        run: node scripts/quora-bot.js
        env:
          QUORA_EMAIL: ${{ secrets.QUORA_EMAIL }}
          QUORA_PASSWORD: ${{ secrets.QUORA_PASSWORD }}
          QUORA_SESSION_TOKEN: ${{ secrets.QUORA_SESSION_TOKEN }}
          RETRY_MAX: 2
