name: Quora Automation

on:
  push:
    branches:
      - main
    paths:
      - "latest-blog.txt"   # Only trigger when blog file is updated

jobs:
  post-to-quora:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer Quora Poster
        env:
          QUORA_EMAIL: ${{ secrets.QUORA_EMAIL }}
          QUORA_PASSWORD: ${{ secrets.QUORA_PASSWORD }}
          QUORA_COOKIE: ${{ secrets.QUORA_COOKIE }}
        run: node quora.js
